entrypoint: bundle exec rackup -p $PORT
env: flex
runtime: ruby

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  SECRET_KEY_BASE: ENV['app_secret_key']
  DB_USERNAME: ENV['production_db_username']
  DB_PASSWORD: ENV['production_db_password']
  DEVISE_KEY: ENV['device_secret_key']

beta_settings:
        cloud_sql_instances: cascadesclinic-197917:us-central1:cascades-clinic  
